In [ ]:
import pandas as pd
import os

directory = 'Mass_Shootings_CSV'
dataframes = []

for year in range(2014, 2023):
    filename = os.path.join(directory, f'{year}.csv')

    if os.path.isfile(filename):
        df = pd.read_csv(filename)
        dataframes.append(df)

appended_data = pd.concat(dataframes, ignore_index=True)
output_csv_file = 'Mass_Shootings_Year-2014_to_2022.csv'


appended_data.to_csv(output_csv_file, index=False)
print(f'Combined data saved to {output_csv_file}')

Combined data saved to Mass_Shootings_Year-2014_to_2022.csv

In [ ]:
df = pd.read_csv('Mass_Shootings_Year-2014_to_2022.csv')

In [ ]:
df.head(-5)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,271363,"December 29, 2014",Louisiana,New Orleans,Poydras and Bolivar,0,4,0,0,0,NaN
1,269679,"December 27, 2014",California,Los Angeles,8800 block of South Figueroa Street,1,3,0,0,0,NaN
2,270036,"December 27, 2014",California,Sacramento,4000 block of May Street,0,4,0,0,0,NaN
3,269167,"December 26, 2014",Illinois,East St. Louis,2500 block of Summit Avenue,1,3,0,0,0,NaN
4,268598,"December 24, 2014",Missouri,Saint Louis,18th and Pine,1,3,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4017,2205024,"January 4, 2022",Mississippi,Jackson,3207 W Capitol St,1,3,0,0,0,NaN
4018,2202976,"January 2, 2022",Texas,Corsicana,1100 block of S 29th St,2,2,0,0,1,NaN
4019,2202727,"January 2, 2022",Texas,San Antonio,427 Montrose,2,2,0,0,0,NaN
4020,2202025,"January 1, 2022",Missouri,Columbia,122 S 9th St,0,4,0,0,1,NaN
4021,2202001,"January 1, 2022",Illinois,Peoria,2000 block of SW Adams St,2,2,0,0,1,NaN